[package]
name = "kat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["string"] }
dirs = "6.0.0"
env_logger = "0.11.6"
eyre = "0.6.12"
glob = "0.3.2"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
